version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data/mariadb"

networks:
  network-inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:0.1
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    depends_on:
      - db
        # condition: service_healthy
    build: ./requirements/wordpress/.
    image: wordpress:0.1
    env_file: .env
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  db:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:0.1
    # healthcheck:
    #   test: ["CMD", "mariadb", "-e", "SELECT 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    env_file: .env
    networks:
      - network-inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always