version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data"

networks:
  nginx-wordpress:
    driver: bridge
  worpress-db:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:0.1
    ports:
      - "443:443"
    networks:
      - nginx-wordpress
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build: ./requirements/wordpress/.
    image: wordpress:0.1
    ports:
      - "9000:9000"
    networks:
      - nginx-wordpress
      - worpress-db
  # db: