version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data/mariadb"

networks:
  network-inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:0.1
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    depends_on:
      - db
      - redis
    build: ./requirements/wordpress/.
    image: wordpress:0.1
    env_file: .env
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  db:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:0.1
    env_file: .env
    networks:
      - network-inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    image: redis:0.1
    env_file: .env
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    image: ftp:0.1
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer:0.1
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - network-inception
    restart: always
