version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/tiago/data"

networks:
  network-inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:0.1
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    # depends_on:
    #   - db
    build: ./requirements/wordpress/.
    image: wordpress:0.1
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "3306:3306"
    networks:
      - network-inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  # db:
  #   container_name: mariadb
  #   build: ./requirements/mariadb/.
  #   image: mariadb:0.1
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - network-inception
  #   volumes:
  #     - mariadb:/var/lib/mysql
  #   restart: always